# Site settings
# These are used to personalize your new site. If you look in _sass/variables.scss, you will see how these are used.
#
# Minimal Mistakes is a popular Jekyll theme, and we'll start with its base
# features and then customize it to your liking.

# Basic Site Information
title: Alejandra Sam - Personal Portfolio
tagline: "Your tagline here, e.g., Researcher | Developer | Designer"
description: >- # this means to ignore newlines until "baseurl:"
  This is a personal portfolio website showcasing projects, research, and interests.
  It's built with Jekyll and the Minimal Mistakes theme, customized for a modern academic/personal look.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alejandresam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "alejandresam/alejandresam.github.io" # Your GitHub username/repo name
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Theme configuration (Minimal Mistakes specific)
minimal_mistakes_skin: "default" # Possible values: "default", "air", "aqua", "contrast", "dark", "dirt", "external", "mint", "sunrise"
                                 # We'll start with default and customize.
remote_theme: "mmistakes/minimal-mistakes@4.26.2" # Use the remote theme for GitHub Pages compatibility

# Site Author Information
author:
  name: "Alejandra Sam"
  avatar: "/assets/images/Samantha_headshot.jpg" # You'll need to add a photo here
  bio: "Brief bio or current role. E.g., PhD Student at University of California, Los Angeles."
  location: "Los Angeles, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your_email@example.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alejandresam"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/samanthaalejandre"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square" # Academicons are supported!
      url: "https://scholar.google.com/citations?user=YOUR_SCHOLAR_ID"
    # Add other links as desired (e.g., Twitter, ResearchGate, personal website)

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5 # number of posts to show per page
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme # Required for remote_theme on GitHub Pages
  - jekyll-seo-tag # For better SEO (search engine optimization)

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be re-enabled by adding them to the `include:` list of the
# configuration file.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Header Navigation (main menu)
# This will be your primary navigation bar.
# We'll create these pages in the next steps.
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Publications"
    url: "/publications/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "CV"
    url: "/assets/cv/CV_Samantha_Alejandre.pdf" # You'll need to upload your CV here
defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      # Add these lines for header background and overlay on pages
      header:
        overlay_color: "#5e636b" # Dark grey overlay (adjust as desired)
        overlay_filter: 0.5 # 50% opacity
        # You can add a default overlay_image here too if you want all pages to have one
        # overlay_image: /assets/images/header-banner.jpg
