

tagline: "Electrical & Computer Engineering M.S. Student | Machine Learning Researcher" # Consistent with your about page
description: >- # this means to ignore newlines until "baseurl:"
  Personal portfolio showcasing projects, research, interests, and insights in Machine Learning, Data Science, and Artificial Intelligence.
  Built with Jekyll and customized for a clean, modern academic/personal look.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://alejandresam.github.io" # the base hostname & protocol for your site, e.g., http://example.com
repository: "alejandresam/alejandresam.github.io" # Your GitHub username/repo name
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Theme configuration (Minimal Mistakes specific)
title: "Samantha Alejandre" #minimal_mistakes_skin: "air" # Attempting to use the Minimal Mistakes "mint" skin
remote_theme: "mmistakes/minimal-mistakes@4.26.2" # Use the remote theme for GitHub Pages compatibility

# Site Author Information
author:
  name: "Samantha Alejandre"
  avatar: "/assets/images/Samantha_headshot.jpg" # Ensure this path is correct and image exists!
  bio: "Electrical & Computer Engineering M.S. Student and Researcher at UCLA. Interested in Machine Learning, Data Science, and AI."
  location: "Los Angeles, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:alejandresam@g.ucla.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alejandresam"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/samanthaalejandre"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar-square" # Academicons are supported!
      url: "https://scholar.google.com/citations?user=YOUR_SCHOLAR_ID" # IMPORTANT: Update YOUR_SCHOLAR_ID
    - label: "CV" # Added CV link here for sidebar as well
      icon: "ai ai-cv-square" # Using an academicons icon for CV
      url: "/assets/cv/CV_Samantha_Alejandre_Resume.pdf" # Link to your PDF

# Navigation (for top menu)
navigation:
  main: # This 'main' key corresponds to the 'main:' in _data/navigation.yml
    - title: "About"
      url: /about/
    - title: "Projects"
      url: /projects/
    - title: "Publications"
      url: /publications/
    - title: "Blog"
      url: /blog/
    - title: "Hobbies"
      url: /hobbies/
    - title: "CV"
      url: /assets/cv/CV_Samantha_Alejandre_Resume.pdf # Link to your PDF


# Build settings
markdown: kramdown
sass:
  load_paths:
    - _sass 
    - assets/css
    # Custom Sass directory for your styles
sass_dir: _sass # Directory for Sass files
style: compressed # Use compressed style for production to reduce file size
  # Use compressed style for production to reduce file size 

highlighter: rouge
permalink: /:categories/:title/
paginate: 5 # number of posts to show per page
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme # Required for remote_theme on GitHub Pages
  - jekyll-seo-tag # For better SEO (search engine optimization)
  - jekyll-last-modified-at # New plugin for displaying last modified date on posts/pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be re-enabled by adding them to the `include:` list of the
# configuration file.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
# These are crucial for applying layouts and other settings automatically to your content.
defaults:
  
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      # Updated header for pages to match minimalist mint theme
    header:
      #overlay_image: /assets/images/banner3.jpg # Path to your banner image
      #overlay_color: "#000" # Or a dark color to blend with the image
      overlay_filter: 0.5 # Adjust for desired overlay darkness