name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # Or 'master' if that's your default branch name for your repository

jobs:
  jekyll:
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write # This line grants write access to the repository contents
      pages: write    # Recommended for GitHub Pages deployments
      id-token: write # Recommended for OIDC authentication with Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Using a specific Ruby 3.x version (e.g., 3.2.x)
          bundler-cache: true # Installs gems defined in Gemfile.lock

      - name: Install Jekyll and dependencies
        run: |
          # The bundler-cache step above handles 'bundle install --path vendor/bundle'
          # We just need to make sure Bundler itself is updated if needed
          gem install bundler
          # Ensure Jekyll is available via bundler
          bundle config set --local path 'vendor/bundle' # Set bundle path
          bundle install # Install gems based on Gemfile.lock

      - name: Build Jekyll site
        run: bundle exec jekyll build # --verbose can be added for more debugging info

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Using a common action for deployment
        if: github.ref == 'refs/heads/main' # Only deploy from your main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # The directory Jekyll outputs to
          # Optional: Configure this action to use the GitHub Pages token
          # You might not need this if `pages: write` above is sufficient,
          # but some setups specifically require it for more secure deployment.
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # If you're using a deploy key
          # enable_html_check: false # Set to false to skip HTML checks if causing issues